# Generated by Django 3.2.6 on 2021-09-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Instrument description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataCube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', max_length=191, unique=True, verbose_name='Observation ID')),
                ('filename', models.CharField(help_text='File name including .FITS extension', max_length=512)),
                ('path', models.FilePathField(help_text='Full path to the file', max_length=512)),
                ('size', models.PositiveBigIntegerField(help_text='Size of the file in bytes')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.instrument')),
                ('tags', models.ManyToManyField(related_name='cubes', to='observations.Tag')),
            ],
        ),
    ]
