# Generated by Django 3.2.6 on 2021-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacube',
            name='path',
            field=models.FilePathField(editable=False, help_text='Full path to the file', max_length=512),
        ),
    ]
