# Generated by Django 3.2.6 on 2021-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_datacube_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.IntegerField(choices=[(1, 'Feature'), (2, 'Event')], default=1),
            preserve_default=False,
        )
    ]
