# Generated by Django 3.2.6 on 2021-10-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20211022_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(db_index=True, help_text='Point ID indicating the pointing and acting as a group identifier for multi-cubeobservations', max_length=191, unique=True, verbose_name='Point ID')),
            ],
        ),
        migrations.AddField(
            model_name='datacube',
            name='observation',
            field=models.ForeignKey(help_text='Parent observation this DataCube belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cubes', to='observations.observation'),
        ),
    ]
