# Generated by Django 3.2.6 on 2021-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20211027_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacube',
            name='grouping_tag',
            field=models.CharField(choices=[('grouped', 'Grouped'), ('mosaic', 'Mosaic')], help_text='Tag that describes if the grouping relationship to the parent observation. See the GroupTag choices for more information', max_length=16, null=True),
        ),
    ]
