# Generated by Django 3.2.6 on 2021-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_datacube_grouping_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacube',
            name='grouping_tag',
            field=models.CharField(choices=[('grouped', 'Grouped'), ('mosaic', 'Mosaic')], default=None, help_text='Tag that describes if the grouping relationship to the parent observation. See the GroupTag choices for more information', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='datacube',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='cubes', to='observations.Tag'),
        ),
    ]
