# Generated by Django 3.2.6 on 2021-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20211027_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacube',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cubes', to='observations.Tag'),
        ),
    ]
