# Generated by Django 3.2.6 on 2021-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_alter_datacube_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacube',
            name='grouping_tag',
            field=models.CharField(blank=True, choices=[('grouped', 'Grouped'), ('mosaic', 'Mosaic')], default=None, help_text='Tag that describes if the grouping relationship to the parent observation. See the GroupTag choices for more information', max_length=16, null=True),
        ),
    ]
