# Generated by Django 3.2.6 on 2021-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_alter_datacube_grouping_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='date_beg',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='Observation began'),
        ),
        migrations.AddField(
            model_name='observation',
            name='date_end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='Observation ended'),
        )
    ]
