# Generated by Django 3.2.6 on 2021-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20211115_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacube',
            name='events_ingested',
            field=models.BooleanField(default=False, help_text='If a proper list of EVENTS was present in the data cube this willbe set to True', verbose_name='Events have been ingested'),
        ),
        migrations.AddField(
            model_name='datacube',
            name='features_ingested',
            field=models.BooleanField(default=False, help_text='If a proper list of FEATURES was present in the data cube thiswill be set to True', verbose_name='Features have been ingested'),
        ),
    ]
