# Generated by Django 3.2.6 on 2021-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_field', models.TextField(blank=True, help_text='New Test Field', null=True, verbose_name='NEW_FIELD')),
            ],
        ),
    ]
