# Generated by Django 3.2.6 on 2021-09-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=191, verbose_name='Relative URL to image preview')),
                ('image_path', models.CharField(max_length=191, verbose_name='Absolute path to image on disk')),
                ('data_cube', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='observations.datacube')),
            ],
        ),
        migrations.CreateModel(
            name='AnimatedGifPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animated_gif', models.CharField(max_length=191, verbose_name='URL to animated GIF')),
                ('data_cube', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animated_preview', to='observations.datacube')),
            ],
        ),
    ]
