# Generated by Django 3.2.6 on 2021-09-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_migrate_data'),
        ('extra_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animatedgifpreview',
            name='data_cube',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animated_preview', to='observations.datacube'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='data_cube',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='observations.datacube'),
        ),
    ]
