# Generated by Django 3.2.6 on 2021-09-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_alter_datalocation_unique_together'),
        ('extra_data', '0003_alter_extradata_data_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='dataset.datalocation')),
            ],
        ),
        migrations.CreateModel(
            name='AnimatedGifPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animated_gif', models.CharField(max_length=255, verbose_name='URL to animated GIF')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animated_preview', to='dataset.datalocation')),
            ],
        ),
    ]
