# Generated by Django 3.2.6 on 2021-09-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0003_reference_data_cube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animatedgifpreview',
            name='data_location',
        ),
        migrations.RemoveField(
            model_name='imagepreview',
            name='data_location',
        ),
    ]
