# Generated by Django 3.2.6 on 2021-09-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_alter_datalocation_unique_together'),
        ('extra_data', '0004_animatedgifpreview_thumbnailpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatedgifpreview',
            name='data_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animated_preview', to='dataset.datalocation'),
        ),
    ]
