# Generated by Django 3.2.6 on 2021-09-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_alter_datalocation_unique_together'),
        ('extra_data', '0006_auto_20210910_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepreview',
            name='data_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='dataset.datalocation'),
        ),
    ]
