# Generated by Django 3.2.6 on 2021-09-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0007_alter_imagepreview_data_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraData',
        ),
    ]
