# Generated by Django 3.2.6 on 2021-09-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0008_observationspectralline_spectralline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spectralline',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ObservationSpectralLine',
        ),
        migrations.DeleteModel(
            name='SpectralLine',
        ),
    ]
