# Generated by Django 3.2.6 on 2021-11-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211117_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, help_text='University or research center affiliation', max_length=100, null=True),
        ),
    ]
