# Generated by Django 3.2.6 on 2021-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211118_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_reverification_disabled',
            field=models.BooleanField(default=False, help_text="Whether the user's email verification needs to beperiodically renewed"),
        ),
    ]
