# Generated by Django 3.2.6 on 2021-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211119_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_reverification_disabled',
            field=models.BooleanField(default=False, help_text="When checked the user's email address will not need to be periodcally renewed.", verbose_name='E-mail re-verification disabled'),
        ),
    ]
