# Generated by Django 3.2.6 on 2021-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_email_reverification_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, help_text='University affiliation.', max_length=100, null=True),
        ),
    ]
