# Generated by Django 3.2.6 on 2021-10-01 10:56

from django.db import migrations, models
import django.db.models.deletion


def remove_unreferenced_previews(apps, schema_editor):
    AnimatedGifPreview = apps.get_model('previews', 'AnimatedGifPreview')
    ImagePreview = apps.get_model('previews', 'ImagePreview')

    for preview in ImagePreview.objects.all():
        if not preview.data_cube:
            preview.delete()

    for preview in AnimatedGifPreview.objects.all():
        if not preview.data_cube:
            preview.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_datacube_path'),
        ('previews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_unreferenced_previews),
        migrations.AlterField(
            model_name='animatedgifpreview',
            name='animated_gif',
            field=models.TextField(verbose_name='URL to animated GIF'),
        ),
        migrations.AlterField(
            model_name='animatedgifpreview',
            name='data_cube',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animated_preview', to='observations.datacube'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='data_cube',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='observations.datacube'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='image_path',
            field=models.TextField(verbose_name='Absolute path to image on disk'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='image_url',
            field=models.TextField(verbose_name='Relative URL to image preview'),
        ),
    ]
