# Generated by Django 3.2.6 on 2021-10-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0003_r0data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r0data',
            options={'verbose_name': 'R0 Data', 'verbose_name_plural': 'R0 Data'},
        ),
    ]
