# Generated by Django 3.2.6 on 2021-10-15 12:42
import os

from django.core.files import File
from django.db import migrations, models


def migrate_images(apps, schema_editor):
    ImagePreview = apps.get_model('previews', 'ImagePreview')

    for image in ImagePreview.objects.all():
        image.preview.save(os.path.basename(image.image_path),
                           File(open(image.image_path, 'rb'))
                           )
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0004_alter_r0data_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreview',
            name='preview',
            field=models.ImageField(null=True, upload_to='previews/', verbose_name='Preview image stored in the managed upload folder'),
        ),
        migrations.RunPython(migrate_images)
    ]
