# Generated by Django 3.2.6 on 2021-10-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_datacube_path'),
        ('previews', '0008_auto_20211018_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralLineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField(verbose_name='JSON blob with data for the plot')),
                ('data_version', models.IntegerField(verbose_name='Version number that indicates the format of the JSON blob. If the JSON blob data format changes this field should be bumped as well')),
                ('data_cube', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_line_data', to='observations.datacube')),
            ],
            options={
                'verbose_name': 'Spectral Line Data',
                'verbose_name_plural': 'Spectral Line Data',
            },
        ),
    ]
