# Generated by Django 3.2.6 on 2021-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0009_spectrallinedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrallinedata',
            name='data_preview',
            field=models.ImageField(null=True, upload_to='spectral-line/thumbnails/', verbose_name='Small preview image stored in managed upload folder'),
        ),
    ]
