# Generated by Django 3.2.6 on 2021-10-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_datacube_path'),
        ('previews', '0011_remove_animatedgifpreview_animated_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_video', models.ImageField(null=True, upload_to='videos/temporal/', verbose_name='Temporal video stored in upload folder')),
                ('data_cube', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_preview', to='observations.datacube')),
            ],
        ),
    ]
