# Generated by Django 3.2.6 on 2021-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0012_videopreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopreview',
            name='temporal_video',
        ),
        migrations.AddField(
            model_name='videopreview',
            name='video_wings',
            field=models.ImageField(null=True, upload_to='videos/temporal/wings/', verbose_name='Temporal video from wings stored in upload folder'),
        ),
    ]
