# Generated by Django 3.2.6 on 2021-10-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0013_auto_20211025_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimatedGifPreview',
        ),
    ]
