# Generated by Django 3.2.6 on 2021-11-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0014_delete_animatedgifpreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r0data',
            name='data_version',
        ),
        migrations.RemoveField(
            model_name='spectrallinedata',
            name='data_version',
        ),
    ]
