# Generated by Django 3.2.6 on 2021-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0015_auto_20211101_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopreview',
            old_name='video_wings',
            new_name='video_core',
        ),
    ]
