# Generated by Django 3.2.6 on 2021-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0016_auto_20211125_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopreview',
            name='video_core',
            field=models.ImageField(null=True, upload_to='videos/temporal/core/', verbose_name='Temporal video from core stored in upload folder'),
        ),
    ]
