# Generated by Django 3.2.6 on 2021-09-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisp',
            name='data_location',
        ),
        migrations.DeleteModel(
            name='Chromis',
        ),
        migrations.DeleteModel(
            name='Crisp',
        ),
    ]
