# Generated by Django 3.2.6 on 2021-09-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20210930_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='oid',
        ),
    ]
