# Generated by Django 3.2.6 on 2021-09-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_remove_instrument_metadata_content_type'),
        ('metadata', '0002_auto_20210928_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombinedMetadata',
            new_name='Metadata',
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['date_beg'], 'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadata'},
        ),
    ]
