# Generated by Django 3.2.6 on 2021-10-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_datacube_path'),
        ('metadata', '0003_remove_metadata_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data_cube',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='observations.datacube'),
        ),
    ]
