# Generated by Django 3.2.6 on 2021-09-29 13:29

from django.db import migrations, models
import django.db.models.deletion


def reference_data_cubes(apps, schema_editor):
    DataCube = apps.get_model('observations', 'DataCube')
    Metadata = apps.get_model('metadata', 'Metadata')

    for metadata in Metadata.objects.all():
        data_location = metadata.data_location
        filename = data_location.file_name
        cube = DataCube.objects.get(filename=filename)
        metadata.data_cube = cube
        metadata.save()


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_migrate_data'),
        ('metadata', '0003_auto_20210929_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='data_cube',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata', to='observations.datacube'),
        ),
        migrations.RunPython(reference_data_cubes),
    ]
