# Generated by Django 3.2.6 on 2021-09-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_metadata_data_cube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='data_location',
        ),
    ]
