# Generated by Django 3.2.6 on 2021-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210924_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
