# Generated by Django 3.2.6 on 2021-09-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0004_auto_20210915_1342'),
        ('tags', '0003_alter_tagcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'Tag Category', 'verbose_name_plural': 'Tag Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='datalocationtag',
            unique_together={('data_location', 'tag')},
        ),
    ]
