# Generated by Django 3.2.6 on 2021-12-06 13:28

import data_access.models.data_cube_access_token
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('observations', '0012_auto_20211206_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwedishUserValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField(blank=True, null=True, verbose_name='Time and date when validation took place')),
                ('validation_result', models.TextField(choices=[('Not Processed', 'Not Processed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Processed', verbose_name='Validation result')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User requesting Swedish user status')),
            ],
        ),
        migrations.CreateModel(
            name='DataCubeAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_string', models.CharField(default='', help_text='Unique textual representation of token', max_length=191, unique=True, verbose_name='Token String')),
                ('grant_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token was created', verbose_name='Grant Date')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token expires', verbose_name='Expiration date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('data_cube', models.ForeignKey(help_text='The data cube that this token gives provides access to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='observations.datacube', verbose_name='Data Cube')),
            ],
            options={
                'ordering': ['data_cube__filename'],
            },
        ),
        migrations.CreateModel(
            name='DataCubeAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(null=True)),
                ('release_comment', models.TextField(help_text='Comment about the release restrictionsfor this data.', null=True, verbose_name='Release comment')),
                ('original_data_class', models.CharField(choices=[('solarnet', 'Solarnet'), ('swedish_university', 'Swedish University'), ('ipu', 'International Paying University'), ('open', 'Open'), ('unspecified', 'Unspecified')], default='unspecified', max_length=32)),
                ('data_cube', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='observations.datacube')),
            ],
        ),
        migrations.CreateModel(
            name='DataCubeUserGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=190, verbose_name='E-mail address of the user with the grant')),
                ('data_cube', models.ForeignKey(help_text='The data cube that this token gives provides access to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='observations.datacube', verbose_name='Data Cube')),
            ],
            options={
                'ordering': ['user_email'],
                'permissions': (('can_access_protected_data', 'Can access protected data'),),
                'unique_together': {('user_email', 'data_cube')},
            },
        ),
        migrations.CreateModel(
            name='DataCubeGroupGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_grants', to='observations.datacube', verbose_name='Data Cube')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grant this group permission to access the data cube')),
            ],
            options={
                'ordering': ['data_cube__filename'],
                'unique_together': {('group', 'data_cube')},
            },
        ),
    ]
