# Generated by Django 3.2.6 on 2021-09-29 15:14

import data_access.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLocationAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_string', models.CharField(default=data_access.models.generate_token, help_text='Unique textual representation of token', max_length=191, unique=True, verbose_name='Token String')),
                ('grant_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token was created', verbose_name='Grant Date')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token expires', verbose_name='Expiration date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('data_cube', models.ForeignKey(help_text='The data cube that this token gives provides access to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='observations.datacube', verbose_name='Data Cube')),
            ],
        ),
        migrations.CreateModel(
            name='DataLocationAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(null=True)),
                ('release_comment', models.TextField(help_text='Comment about the release restrictionsfor this data.', null=True, verbose_name='Release comment')),
                ('data_cube', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='observations.datacube')),
            ],
        ),
        migrations.CreateModel(
            name='DataLocationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=191, verbose_name='User email')),
                ('data_cube', models.ForeignKey(help_text='The data cube that this token gives provides access to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='observations.datacube', verbose_name='Data Cube')),
            ],
            options={
                'verbose_name': 'Data location access grant',
                'ordering': ['user_email'],
                'permissions': (('can_access_protected_data', 'Can access protected data'),),
                'unique_together': {('user_email', 'data_cube')},
            },
        ),
    ]
