# Generated by Django 3.2.6 on 2021-09-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0002_alter_datalocation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLocationAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(null=True)),
                ('data_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='dataset.datalocation')),
            ],
        ),
        migrations.CreateModel(
            name='DataLocationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200, verbose_name='User email')),
                ('data_location', models.ForeignKey(help_text='The data location that this grant gives the user access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='dataset.datalocation', verbose_name='Data location')),
            ],
            options={
                'verbose_name': 'Data location access grant',
                'ordering': ['user_email'],
                'unique_together': {('user_email', 'data_location')},
            },
        ),
    ]
