# Generated by Django 3.2.6 on 2021-12-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCubeAccessToken',
        ),
    ]
