# Generated by Django 3.2.7 on 2021-09-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalocationaccesstoken',
            name='data_location',
            field=models.ForeignKey(help_text='The data location that this token gives provides access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='dataset.datalocation', verbose_name='Data location'),
        ),
        migrations.AddField(
            model_name='datalocationaccessgrant',
            name='data_location',
            field=models.ForeignKey(help_text='The data location that this grant gives the user access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='dataset.datalocation', verbose_name='Data location'),
        ),
        migrations.AddField(
            model_name='datalocationaccesscontrol',
            name='data_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='dataset.datalocation'),
        ),
        migrations.AlterUniqueTogether(
            name='datalocationaccessgrant',
            unique_together={('user_email', 'data_location')},
        ),
    ]
