# Generated by Django 3.2.6 on 2021-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalocationaccesscontrol',
            name='release_comment',
            field=models.TextField(help_text='Comment about the release restrictionsfor this data.', null=True, verbose_name='Release comment'),
        ),
    ]
