# Generated by Django 3.2.6 on 2021-09-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataLocationAccessControl',
            new_name='DataCubeAccessControl',
        ),
        migrations.RenameModel(
            old_name='DataLocationAccessGrant',
            new_name='DataCubeAccessGrant',
        ),
        migrations.RenameModel(
            old_name='DataLocationAccessToken',
            new_name='DataCubeAccessToken',
        ),
    ]
