# Generated by Django 3.2.6 on 2021-11-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_alter_datacube_grouping_tag'),
        ('data_access', '0002_auto_20210930_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCubeAccessGrant',
            new_name='DataCubeUserGrant',
        ),
    ]
