# Generated by Django 3.2.6 on 2021-09-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0002_datalocationaccesscontrol_release_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalocationaccessgrant',
            options={'ordering': ['user_email'], 'permissions': (('can_access_protected_data', 'Can access protected data'),), 'verbose_name': 'Data location access grant'},
        ),
    ]
