# Generated by Django 3.2.6 on 2021-09-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_alter_datalocation_unique_together'),
        ('data_access', '0003_alter_datalocationaccessgrant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLocationAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(help_text='The time when this access token expires', verbose_name='Expiration date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('data_location', models.ForeignKey(help_text='The data location that this token gives provides access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='dataset.datalocation', verbose_name='Data location')),
            ],
        ),
    ]
