# Generated by Django 3.2.6 on 2021-11-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_alter_datacube_grouping_tag'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data_access', '0003_rename_datacubeaccessgrant_datacubeusergrant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeusergrant',
            options={'ordering': ['user_email'], 'permissions': (('can_access_protected_data', 'Can access protected data'),), 'verbose_name': 'Data Location User Grant'},
        ),
        migrations.AlterField(
            model_name='datacubeusergrant',
            name='data_cube',
            field=models.ForeignKey(help_text='The data cube that this token gives provides access to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='observations.datacube', verbose_name='Data Cube'),
        ),
        migrations.CreateModel(
            name='DataCubeGroupGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_grants', to='observations.datacube', verbose_name='Data Cube')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'Data Location Group Grant',
                'ordering': ['data_cube__filename'],
                'unique_together': {('group', 'data_cube')},
            },
        ),
    ]
