# Generated by Django 3.2.6 on 2021-09-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_migrate_data'),
        ('data_access', '0004_reference_data_cube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalocationaccesscontrol',
            name='data_location',
        ),
        migrations.RemoveField(
            model_name='datalocationaccesstoken',
            name='data_location',
        ),
        migrations.AlterUniqueTogether(
            name='datalocationaccessgrant',
            unique_together={('user_email', 'data_cube')},
        ),
        migrations.RemoveField(
            model_name='datalocationaccessgrant',
            name='data_location',
        ),
    ]
