# Generated by Django 3.2.6 on 2021-09-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_datalocationaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalocationaccesstoken',
            name='grant_date',
            field=models.DateTimeField(help_text='The time and date when this access token was created', null=True, verbose_name='Grant Date'),
        ),
        migrations.AddField(
            model_name='datalocationaccesstoken',
            name='token_string',
            field=models.CharField(help_text='Unique textual representation of token', max_length=255, null=True, unique=True, verbose_name='Token String'),
        ),
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='expiration_date',
            field=models.DateTimeField(help_text='The time and date when this access token expires', null=True, verbose_name='Expiration date'),
        ),
    ]
