# Generated by Django 3.2.6 on 2021-11-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_auto_20211101_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeaccesscontrol',
            options={'ordering': ['data_cube__filename'], 'verbose_name': 'Data Cube Access Control'},
        ),
        migrations.AlterModelOptions(
            name='datacubeaccesstoken',
            options={'ordering': ['data_cube__filename'], 'verbose_name': 'Data Cube Access Token'},
        ),
        migrations.AlterModelOptions(
            name='datacubegroupgrant',
            options={'ordering': ['data_cube__filename'], 'verbose_name': 'Data Cube Group Grant'},
        ),
        migrations.AlterModelOptions(
            name='datacubeusergrant',
            options={'ordering': ['user_email'], 'permissions': (('can_access_protected_data', 'Can access protected data'),), 'verbose_name': 'Data Cube User Grant'},
        ),
    ]
