# Generated by Django 3.2.6 on 2021-09-13 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0005_auto_20210913_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 13, 14, 35, 282171), help_text='The time and date when this access token expires', verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='grant_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 13, 14, 35, 282136), help_text='The time and date when this access token was created', verbose_name='Grant Date'),
        ),
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='token_string',
            field=models.CharField(default='', help_text='Unique textual representation of token', max_length=255, unique=True, verbose_name='Token String'),
        ),
    ]
