# Generated by Django 3.2.6 on 2021-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0005_auto_20211101_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeaccesscontrol',
            options={'verbose_name': 'Data Cube Access Control'},
        ),
        migrations.AddField(
            model_name='datacubeaccesscontrol',
            name='data_class',
            field=models.CharField(choices=[('solarnet', 'Solarnet'), ('swedish_university', 'Swedish University'), ('ipu', 'International Paying University'), ('open', 'Open'), ('unspecified', 'Unspecified')], default='unspecified', max_length=32),
        ),
    ]
