# Generated by Django 3.2.6 on 2021-09-13 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0006_auto_20210913_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token expires', verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='grant_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time and date when this access token was created', verbose_name='Grant Date'),
        ),
    ]
