# Generated by Django 3.2.6 on 2021-11-01 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0010_alter_datacube_grouping_tag'),
        ('data_access', '0006_auto_20211101_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeusergrant',
            options={'ordering': ['user'], 'permissions': (('can_access_protected_data', 'Can access protected data'),), 'verbose_name': 'Data Cube User Grant'},
        ),
        migrations.AddField(
            model_name='datacubeusergrant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User email'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='datacubeusergrant',
            unique_together={('user', 'data_cube')},
        ),
        migrations.RemoveField(
            model_name='datacubeusergrant',
            name='user_email',
        ),
    ]
