# Generated by Django 3.2.6 on 2021-11-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_access', '0007_auto_20211101_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeaccesscontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datacubeaccesstoken',
            options={'ordering': ['data_cube__filename']},
        ),
        migrations.AlterModelOptions(
            name='datacubegroupgrant',
            options={'ordering': ['data_cube__filename']},
        ),
        migrations.AlterModelOptions(
            name='datacubeusergrant',
            options={'ordering': ['user'], 'permissions': (('can_access_protected_data', 'Can access protected data'),)},
        ),
        migrations.RenameField(
            model_name='datacubeaccesscontrol',
            old_name='data_class',
            new_name='original_data_class',
        ),
        migrations.AlterField(
            model_name='datacubeusergrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The User the permission has been granted to'),
        ),
    ]
