# Generated by Django 3.2.6 on 2021-09-13 14:16

import data_access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0007_auto_20210913_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalocationaccesstoken',
            name='token_string',
            field=models.CharField(default=data_access.models.generate_token, help_text='Unique textual representation of token', max_length=255, unique=True, verbose_name='Token String'),
        ),
    ]
