# Generated by Django 3.2.6 on 2021-11-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_access', '0008_auto_20211102_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacubegroupgrant',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grant this group permission to access the data cube'),
        ),
        migrations.AlterField(
            model_name='datacubeusergrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Grant this user permission to access the data cube'),
        ),
    ]
