# Generated by Django 3.2.6 on 2021-11-16 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_access', '0012_alter_swedishcitizenvalidationrequest_validation_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwedishCitizenValidationRequest',
            new_name='SwedishUserValidationRequest',
        ),
    ]
