# Generated by Django 3.2.6 on 2021-11-16 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_access', '0013_rename_swedishcitizenvalidationrequest_swedishuservalidationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swedishuservalidationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User requesting Swedish user status'),
        ),
    ]
