# Generated by Django 3.2.6 on 2021-10-01 10:56

from django.db import migrations, models


def rename_swedish_user_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(name='Swedish Citizen').update(name='Swedish User')


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0014_alter_swedishuservalidationrequest_user'),
    ]

    operations = [
        migrations.RunPython(rename_swedish_user_group),
    ]
