# Generated by Django 3.2.6 on 2021-11-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0015_alter_swedish_user_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='swedishuservalidationrequest',
            name='purpose',
            field=models.CharField(default='', max_length=190, verbose_name='Purpose of the account'),
            preserve_default=False,
        ),
    ]
