# Generated by Django 3.2.6 on 2021-11-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0016_swedishuservalidationrequest_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swedishuservalidationrequest',
            name='purpose',
        ),
    ]
