# Generated by Django 3.2.6 on 2021-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20211115_1250'),
        ('data_access', '0017_remove_swedishuservalidationrequest_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacubeusergrant',
            options={'ordering': ['user_email'], 'permissions': (('can_access_protected_data', 'Can access protected data'),)},
        ),
        migrations.AddField(
            model_name='datacubeusergrant',
            name='user_email',
            field=models.CharField(default='', max_length=190, verbose_name='E-mail address of the user with the grant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='datacubeusergrant',
            unique_together={('user_email', 'data_cube')},
        ),
        migrations.RemoveField(
            model_name='datacubeusergrant',
            name='user',
        ),
    ]
